### ISSUE TITLE
ServiceRouterがなんか落ちるようになった

### ISSUE THREAD

**Issue by pei0804** [pei0804/gameday#11]

**Comment by SRkuma** [comment]
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/service-router/log-events/service-router

**Comment by pei0804** [comment]
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/9821370/100416905-f5c43f80-30c2-11eb-8ec8-7b57d27ba635.png">

**Comment by pei0804** [comment]
SG消されてたので起動設定からやり直した
`service-router-ec2` って

https://console.aws.amazon.com/ec2autoscaling/home?region=us-east-1#/lc?launchConfigurationName=service-router-ec2

<img width="959" alt="image" src="https://user-images.githubusercontent.com/9821370/100419269-974d9000-30c7-11eb-859b-e9d244b13b0e.png">

**Comment by pei0804** [comment]
とりあえず、新しい起動テンプレで動かした
<img width="819" alt="image" src="https://user-images.githubusercontent.com/9821370/100419523-0aef9d00-30c8-11eb-8458-f15efe5fea9c.png">

**Comment by pei0804** [comment]
セキュリティグループの設定破壊されてたのが原因

**Comment by yuitaso** [comment]
要求シミュレーション

```
$curl -d '{"Message":"TestMessage","RequestId":"test","Services":["reverser","swapcaser"]}' -H 'Content-Type: application/json' http://mod-g-loadb-1xb7098z3c6w2-325814934.us-east-1.elb.amazonaws.com/
{"Responses": [{"Message": "646921a7974c4f32b015ed0b396dbe60egasseMtseT", "Signature": "Z9oxPHSpBOTjQG27+3dazTE4kqctx3w0jXS04PSKtZw="}, {"message": "Internal server error"}]}%
```
