### ISSUE TITLE
sg-05d44f1b85f9c4465が消えてる

### ISSUE THREAD

**Issue by pei0804** [pei0804/gameday#13]
これはRedチームかなー

**Comment by pei0804** [comment]
Roleわけとけやあああああああああああああああああああああああ
<img width="960" alt="image" src="https://user-images.githubusercontent.com/9821370/100419408-d67be100-30c7-11eb-859d-d57bd9124baa.png">

https://console.aws.amazon.com/cloudtrail/home?region=us-east-1#/events/122e08ed-3a5d-412b-8412-c59a2fbcf469

**Comment by yuitaso** [comment]
```
$curl -d '{"Message":"TestMessage","RequestId":"test","Services":["reverser","swapcaser"]}' -H 'Content-Type: application/json' http://52.71.113.106
{"Responses": [{"Message": "646921a7974c4f32b015ed0b396dbe60egasseMtseT", "Signature": "Z9oxPHSpBOTjQG27+3dazTE4kqctx3w0jXS04PSKtZw="}, {"message": "Internal server error"}]}%
```
